on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
    steps:
      - name: Setup Sbt
        uses: coursier/setup-action@v1.2.0-M2
        with:
          apps: sbt sbtn


      - run: sbt publish