name: Main merge
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
      BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v2
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: "openjdk@1.17"
      - run: sbt test publishLocal it:test publish
